name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.17

main: ${mainClass}

commands:
    shout:
        description: Shout a message
        permission: mchat.shout
        usage: /<command>
    login:
        description: Login to the chat website using a one time code
        permission: mchat.login
        usage: /<command>
    map:
        description: Add or update a point on the map
        permission: mchat.addpoint
        usage: /<command> [name] [type] [x] [z] [dim]
permissions:
    mchat.shout:
        description: can shout
        default: true
    mchat.login:
        description: can login
        default: true
    mchat.map:
        description: can add points to the map
        default: true
