name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.17

main: ${mainClass}

commands:
    shout:
        description: Shout a message
        permission: mcbot.shout
        usage: /<command>
    login:
        description: Login to the chat website using a one time code
        permission: mcbot.login
        usage: /<command>
permissions:
    mcbot.shout:
        description: can shout
        default: true
    mcbot.login:
        description: can login
        default: true
